#!/usr/bin/env python3
"""generate_bilingual_ass.py — Generate bilingual ASS subtitle with zh-TW + EN.

Default: 22px zh-TW (Noto Sans TC) + 16px EN (Arial), BorderStyle=1 (outline+shadow).
Use --scale to dynamically scale fonts based on video height (default 1080p reference).

Usage:
    python generate_bilingual_ass.py <zh.srt> <en.srt> <output.ass> [options]

Options:
    --background black|none   BorderStyle: none=outline+shadow(default), black=black box
    --scale FLOAT             Font scale factor (e.g. 0.67 for 720p, 2.0 for 2160p)
                              Auto-compute from --video-height if not specified
    --video-height PX         Video height in pixels (auto-scale fonts proportionally)
"""
import sys
import re
import argparse
import os


# ── Reference Sizes (at 1080p) ──
# These are the base sizes.  --scale and --video-height adjust them proportionally.
REF_HEIGHT = 1080
ZH_BASE_SIZE = 22
EN_BASE_SIZE = 16
# MarginV: 中英文使用相同值，確保底部對齊一致，不重疊不脫節
# 中文在中間偏下，英文在中文正下方，靠字型大小自然間距
ZH_MARGINV = 50
EN_MARGINV = 50
ZH_OUTLINE = 2
EN_OUTLINE = 2
ZH_SHADOW = 1
EN_SHADOW = 1


def compute_scale(video_height=None):
    """Compute font scale factor based on video height relative to REF_HEIGHT (1080p)."""
    if video_height is None or video_height <= 0:
        return 1.0
    scale = video_height / REF_HEIGHT
    # Clamp to reasonable range (480p – 4320p)
    return max(0.44, min(4.0, scale))


def style_header(background, scale, play_res_y=REF_HEIGHT):
    """Build ASS [Script Info] and [V4+ Styles] section.

    Args:
        background: "none" or "black"
        scale: font scale factor
    """
    zh_fs = round(ZH_BASE_SIZE * scale)
    en_fs = round(EN_BASE_SIZE * scale)
    zh_mv = round(ZH_MARGINV * scale)
    en_mv = round(EN_MARGINV * scale)
    zh_ol = max(1, round(ZH_OUTLINE * scale))
    en_ol = max(1, round(EN_OUTLINE * scale))
    zh_sh = max(0, round(ZH_SHADOW * scale))
    en_sh = max(0, round(EN_SHADOW * scale))

    # PrimaryColour: white (&H00FFFFFF)
    # SecondaryColour: blue (&H000000FF)
    # OutlineColour: black (&H00000000)

    if background == "black":
        # BorderStyle=4: opaque black box behind text
        # BackColour: semi-transparent black (&H80000000)
        zh_bg = "&H80000000"
        en_bg = "&H80000000"
        bstyle = 4
        zh_outline = 0
        en_outline = 0
        zh_shadow = 0
        en_shadow = 0
    else:
        # BorderStyle=1: outline + shadow, fully transparent background
        zh_bg = "&H00000000"
        en_bg = "&H00000000"
        bstyle = 1
        zh_outline = zh_ol
        en_outline = en_ol
        zh_shadow = zh_sh
        en_shadow = en_sh

    play_res_x = round(play_res_y * 16 / 9)

    return f"""[Script Info]
; Script generated by generate_bilingual_ass.py
; Font: zh-TW={zh_fs}px, EN={en_fs}px (scale={scale:.2f})
; Background: BorderStyle={bstyle} ({background})
ScriptType: v4.00+
PlayResX: {play_res_x}
PlayResY: {play_res_y}
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: zh-TW,Noto Sans TC,{zh_fs},&H00FFFFFF,&H000000FF,&H00000000,{zh_bg},1,0,0,0,100,100,0,0,{bstyle},{zh_outline},{zh_shadow},2,40,40,{zh_mv},1
Style: EN,Arial,{en_fs},&H00FFFFFF,&H000000FF,&H00000000,{en_bg},0,0,0,0,100,100,0,0,{bstyle},{en_outline},{en_shadow},2,40,40,{en_mv},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def parse_srt(path):
    """Parse SRT file into list of (time_range, text)."""
    with open(path, 'r', encoding='utf-8-sig') as f:
        content = f.read()

    blocks = re.split(r'\r?\n\s*\r?\n', content.strip())
    entries = []
    for block in blocks:
        lines = block.strip().splitlines()
        if len(lines) >= 3 and ' --> ' in lines[1]:
            time_range = lines[1].strip()
            text = '\n'.join(lines[2:]).strip()
            if text:
                entries.append((time_range, text))
    return entries


def srt_time_to_ass(st):
    """Convert SRT timestamp to ASS format.

    SRT: 00:01:23,456
    ASS: 0:01:23.46
    """
    m = re.fullmatch(r'(\d+):([0-5]\d):([0-5]\d)[,.](\d{1,3})', st.strip())
    if not m:
        raise ValueError(f"Invalid SRT timestamp: {st!r}")

    h, mi, s = int(m.group(1)), int(m.group(2)), int(m.group(3))
    ms = int(m.group(4).ljust(3, '0'))
    total_ms = (((h * 60 + mi) * 60) + s) * 1000 + ms
    total_cs = (total_ms + 5) // 10
    out_h, remainder = divmod(total_cs, 360000)
    out_m, remainder = divmod(remainder, 6000)
    out_s, centiseconds = divmod(remainder, 100)
    return f"{out_h}:{out_m:02d}:{out_s:02d}.{centiseconds:02d}"


def srt_time_range_ms(time_range):
    """Convert an SRT time range into integer start/end milliseconds."""
    try:
        start_text, end_text = time_range.split(' --> ', 1)
    except ValueError as exc:
        raise ValueError(f"Invalid SRT time range: {time_range!r}") from exc

    def to_ms(value):
        match = re.fullmatch(r'(\d+):([0-5]\d):([0-5]\d)[,.](\d{1,3})', value.strip())
        if not match:
            raise ValueError(f"Invalid SRT timestamp: {value!r}")
        hours, minutes, seconds = map(int, match.groups()[:3])
        milliseconds = int(match.group(4).ljust(3, '0'))
        return (((hours * 60 + minutes) * 60) + seconds) * 1000 + milliseconds

    start_ms, end_ms = to_ms(start_text), to_ms(end_text)
    if end_ms <= start_ms:
        raise ValueError(f"SRT end must be after start: {time_range!r}")
    return start_ms, end_ms


def align_english_to_chinese(
    zh_entries,
    en_entries,
    max_center_diff_ms=1500,
    min_overlap_ms=250,
    min_overlap_ratio=0.2,
):
    """Assign each English segment to the best overlapping Chinese segment."""
    groups = [[] for _ in zh_entries]
    unmatched = []
    zh_ranges = [srt_time_range_ms(time_range) for time_range, _ in zh_entries]

    for en_entry in en_entries:
        en_start, en_end = srt_time_range_ms(en_entry[0])
        en_center = (en_start + en_end) / 2
        substantial_indexes = []
        best_index = None
        best_overlap = 0
        best_center_diff = float('inf')
        en_duration = en_end - en_start

        for index, (zh_start, zh_end) in enumerate(zh_ranges):
            overlap = max(0, min(zh_end, en_end) - max(zh_start, en_start))
            center_diff = abs(((zh_start + zh_end) / 2) - en_center)
            zh_duration = zh_end - zh_start
            overlap_ratio = max(overlap / en_duration, overlap / zh_duration)
            if overlap >= min_overlap_ms and overlap_ratio >= min_overlap_ratio:
                substantial_indexes.append(index)
            if overlap > best_overlap or (
                overlap == best_overlap and center_diff < best_center_diff
            ):
                best_index = index
                best_overlap = overlap
                best_center_diff = center_diff

        if substantial_indexes:
            # Reuse a long translation across every Chinese segment it spans.
            # This preserves content when Whisper splits the two languages
            # differently and avoids silently dropping the translation.
            for index in substantial_indexes:
                groups[index].append(en_entry)
        elif best_index is not None and (
            best_overlap > 0 or best_center_diff <= max_center_diff_ms
        ):
            groups[best_index].append(en_entry)
        else:
            unmatched.append(en_entry)

    return groups, unmatched


def strip_html_tags(text):
    """Remove common HTML-like tags from subtitle text."""
    return re.sub(r'</?(?:i|b|u)>', '', text, flags=re.IGNORECASE)


def escape_ass_text(text):
    """Escape subtitle text so it cannot become an ASS override block."""
    text = strip_html_tags(text)
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    # ASS has no portable escape for literal override braces. Use visually
    # equivalent full-width characters so subtitle content cannot inject tags.
    text = text.replace('\\', '＼').replace('{', '｛').replace('}', '｝')
    return text.replace('\n', r'\N')


def generate_ass(zh_entries, en_entries, background="none", video_height=None, scale=None):
    """Generate ASS content from zh-TW and EN SRT entries.

    Args:
        zh_entries: List of (time_range, text) for Chinese
        en_entries: List of (time_range, text) for English
        background: "none" for BorderStyle=1 (transparent), "black" for BorderStyle=4 (black box)
        video_height: Target video height used for ASS PlayRes and auto-scaling
        scale: Explicit font scale factor; takes precedence over auto-scaling

    Returns:
        ASS content string
    """
    if scale is None:
        scale = compute_scale(video_height)
    play_res_y = video_height or REF_HEIGHT
    header = style_header(background, scale, play_res_y=play_res_y)

    lines = [header]
    english_groups, unmatched_english = align_english_to_chinese(zh_entries, en_entries)

    for index, (z_time, z_text) in enumerate(zh_entries):

        # Use Chinese timestamps
        start = srt_time_to_ass(z_time.split(' --> ')[0])
        end = srt_time_to_ass(z_time.split(' --> ')[1])

        z_clean = escape_ass_text(z_text)
        english_text = ' '.join(text for _, text in english_groups[index])

        if english_text:
            e_clean = escape_ass_text(english_text)
            lines.append(f"Dialogue: 0,{start},{end},zh-TW,,0,0,0,,{z_clean}" + r"\N{\rEN}" + e_clean)
        else:
            lines.append(f"Dialogue: 0,{start},{end},zh-TW,,0,0,0,,{z_clean}")

    if unmatched_english:
        print(
            f"WARNING: {len(unmatched_english)} English entries had no Chinese time match",
            file=sys.stderr,
        )
        for e_time, e_text in unmatched_english:
            start = srt_time_to_ass(e_time.split(' --> ')[0])
            end = srt_time_to_ass(e_time.split(' --> ')[1])
            e_clean = escape_ass_text(e_text)
            lines.append(f"Dialogue: 0,{start},{end},EN,,0,0,0,,{e_clean}")

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate bilingual ASS subtitle (zh-TW + EN) with dynamic font scaling"
    )
    parser.add_argument("zh_srt", help="Chinese SRT file")
    parser.add_argument("en_srt", help="English SRT file")
    parser.add_argument("output", help="Output ASS file")
    parser.add_argument(
        "--background", choices=["black", "none"], default="none",
        help="none=outline+shadow only (default), black=black box behind text"
    )
    parser.add_argument(
        "--scale", type=float, default=None,
        help="Font scale factor (default=1.0 at 1080p, auto from --video-height)"
    )
    parser.add_argument(
        "--video-height", type=int, default=None,
        help="Video height in pixels (e.g. 720 for 1280x720). Auto-computes font scale."
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing output file")
    args = parser.parse_args()
    if args.scale is not None and args.scale <= 0:
        parser.error("--scale must be greater than zero")
    if args.video_height is not None and args.video_height <= 0:
        parser.error("--video-height must be greater than zero")
    if os.path.exists(args.output) and not args.force:
        parser.error(f"Output already exists: {args.output}. Use --force to overwrite it.")

    # Compute scale from video-height if --scale not given
    scale = args.scale
    if scale is None:
        scale = compute_scale(args.video_height)

    zh = parse_srt(args.zh_srt)
    en = parse_srt(args.en_srt)
    if not zh:
        parser.error(f"No valid subtitle entries found in {args.zh_srt}")
    if not en:
        parser.error(f"No valid subtitle entries found in {args.en_srt}")

    print(f"Chinese SRT: {len(zh)} entries")
    print(f"English SRT: {len(en)} entries")
    print(f"Background: {args.background}")
    print(f"Font scale: {scale:.2f}")
    if args.video_height:
        print(f"Video height: {args.video_height}px -> zh={round(ZH_BASE_SIZE * scale)}px, en={round(EN_BASE_SIZE * scale)}px")
    else:
        print(f"Base sizes (1080p ref): zh={ZH_BASE_SIZE}px, en={EN_BASE_SIZE}px")
        print(f"  With --video-height 720: zh={round(ZH_BASE_SIZE * compute_scale(720))}px, en={round(EN_BASE_SIZE * compute_scale(720))}px")
        print(f"  With --video-height 2160: zh={round(ZH_BASE_SIZE * compute_scale(2160))}px, en={round(EN_BASE_SIZE * compute_scale(2160))}px")

    ass_content = generate_ass(zh, en, background=args.background, video_height=args.video_height, scale=scale)

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(ass_content)

    print(f"\nBilingual ASS saved to {args.output}")


if __name__ == '__main__':
    main()
